# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 888dc7b548d8d339cf490dacc965e893d0ff73deb87dfa3dabf3f302620e5b77aeb05c2bdcbbf82a404536e1e7bb11851c32ff88b3082eb1693863c50d6b89b2

test:
  secret_key_base: 6f448bb6eed89488ed62b50b78bfd056f8998ad5f6b9778928071b82aa1de7c9d5c84aaf086420ac488b98015b7e2bb88e4fc77f0972b3b5c20b98a49afc944a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
